### ISSUE TITLE
release and deploy to maven repo

### ISSUE THREAD

**Issue by javathought** [binout/livingdoc-maven-plugin#2]
Deploy the plugin artifact to maven repo to make it available
Make a first release (required to deploy)

[Guide to uploading artifacts to the Central Repository](https://maven.apache.org/guides/mini/guide-central-repository-upload.html)

**Comment by binout** [comment]
do we need to have a website "livingdocumentation.org" to reserve the groupId "org.livingdocumentation" ?

**Comment by javathought** [comment]
Reading [maven documentation](https://maven.apache.org/guides/mini/guide-naming-conventions.html), it should : 

> It has to follow the package name rules, what means that has to be at least as a domain name you control

**Comment by javathought** [comment]
Sample prices : 

**1&1  (base price - offered price)**

.org : 12,99 € - 7,99 € HT/an (9,59 € TTC/an)
.com : 9,99 € - 0,99 € HT/an (1,19 € TTC/an)  (first year)

**godaddy  (base price - offered price)**

.org : 14,99 € 0,99 € (1st year, 2 years min)
.com : 14,99 € 0,99 € (1st year, 2 years min)

**gandi.net  (base price - offered price)**

.org : 15,20 € - 7,60 € 
.com : 12,54 €

**Comment by javathought** [comment]
from [guideline for choosing the coordinates](http://central.sonatype.org/pages/choosing-your-coordinates.html), it can be : 
github.com/yourusername -> com.github.yourusername

so a proposal can be : _com.github.livingdocumentation_

**Comment by binout** [comment]
or better : io.github.livingdocumentation ?

**Comment by javathought** [comment]
with github pages ?

**Comment by binout** [comment]
Yes, just need to create a repository called "livingdocumentation.github.com"  and automatically, a website is available on "http://livingdocumentation.github.io".

For instance, http://binout.github.io/ is a website for https://github.com/binout/binout.github.com

**Comment by javathought** [comment]
I know : mine is https://javathought.github.io (with hub press too).

I'll try to release a 0.1 with io.github.livingdocumentation

**Comment by javathought** [comment]
Ready to deploy. An account to sonatype is needed to deploy with the url https://issues.sonatype.org/secure/Signup!default.jspa 

I like GitFlow so I added JGitFlow to automate the release process.

**Comment by javathought** [comment]
Plugin available in maven central

**Comment by binout** [comment]
well done !
