### ISSUE TITLE
Add documentation of maven plugin

### ISSUE THREAD

**Issue by binout** [binout/livingdoc-maven-plugin#6]
Generate documentation of maven plugin and publish it to gh-pages of repository.

https://maven.apache.org/guides/development/guide-plugin-documentation.html

**Comment by binout** [comment]
I find this plugin to publish on gh-pages 
https://github.github.com/maven-plugins/site-plugin/quickstart.html

i'm about to commit a first version of site ;-)

**Comment by binout** [comment]
I commit a first configuration for maven site. I re-use the existing documentation of README in site.
Then i will publish it to gh-pages of repository.

**Comment by javathought** [comment]
I think the related "release maven site" should not be in readme.adoc.  We should limit this document for the user of the plugin. 

I suggest to put such documentation in wiki.
