### ISSUE TITLE
Apply gitflow

### ISSUE THREAD

**Issue by javathought** [binout/livingdoc-maven-plugin#8]
I began applying gitflow (and jgitflow maven plugin).

I propose to change the default branch to develop (so commit merge to develop will automatically closes issues without waiting merge to master)

**Comment by binout** [comment]
ok, let's try.
i just need some advices to deal an issue :
- i need to create a feature branch from develop ?
- then it will be pushed to develop ?
- who merge to master ?

**Comment by javathought** [comment]
The plugin handles all : https://bitbucket.org/atlassian/jgit-flow/wiki/goals.wiki#!goals-overview.

There's also an add-on for git CLI, or SourceTree as the commands embedded.

When you release with `jgitflow:release-start` and `jgitflow:release-finish`, it will merge to master, increase version, build, package, ... and deploy to the repository

_Additional informations_
http://nvie.com/posts/a-successful-git-branching-model/
http://danielkummer.github.io/git-flow-cheatsheet/

**Comment by binout** [comment]
Default branch is now develop.
And master branch is now protected

**Comment by binout** [comment]
We can close issue, ok ?

**Comment by javathought** [comment]
I agree
